name: Run test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.2.0
      with:
        chrome-version: stable
    - run: chrome --version
    
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Maven version
      run: mvn --version
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Merge PR if successful
      if: success()
      id: automerge
      uses: pascalgn/automerge-action@v0.15.6
      env:
        GITHUB_TOKEN: "${{ secrets.PERMISSION }}"
        MERGE_LABELS: ""
